version: '3.1'
services:
  plex-auto-genres:
    container_name: plex-auto-genres
    image: frank2312/plex-auto-genres:latest
    restart: unless-stopped
    volumes:
      - /config:/config
      - /posters:/posters
      - /logs:/logs
    environment:
      - PLEX_USERNAME=xxx
      - PLEX_PASSWORD=xxx
      - PLEX_SERVER_NAME=xxx
      - PLEX_BASE_URL="http://1.2.3.4:32400"
      - PLEX_TOKEN=xxx
      - PLEX_COLLECTION_PREFIX = ""
      - TMDB_API_KEY=xxx